# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Wedge and Hope
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  a jekyll website starter template for creating webcomics
baseurl: 

permalink: 	/:categories/:title/

# Build settings
markdown: kramdown
